version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: npm
    versions:
    - 7.10.0
    - 7.11.0
    - 7.5.2
    - 7.5.3
    - 7.5.4
    - 7.5.6
    - 7.6.0
    - 7.6.1
    - 7.6.2
    - 7.6.3
    - 7.7.0
    - 7.7.4
    - 7.7.5
    - 7.7.6
    - 7.8.0
    - 7.9.0
  - dependency-name: sweetalert2
    versions:
    - 10.13.3
    - 10.14.0
    - 10.14.1
    - 10.15.0
    - 10.15.1
    - 10.15.2
    - 10.15.5
    - 10.15.6
    - 10.15.7
    - 10.16.0
    - 10.16.2
    - 10.16.3
    - 10.16.4
    - 10.16.5
  - dependency-name: firebase
    versions:
    - 8.2.10
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.9
    - 8.3.0
    - 8.3.1
    - 8.3.2
    - 8.3.3
    - 8.4.1
  - dependency-name: react-datepicker
    versions:
    - 3.4.1
    - 3.5.0
    - 3.6.0
    - 3.7.0
  - dependency-name: socket.io-client
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: socket.io
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
