import React from 'react';

export default function RentalAgreement (){
    return (
        <div className='terms-body'>
            <h1>Rental Agreement</h1>
            <h2>IMPORTANT – PLEASE READ THIS CAREFULLY BEFORE AGREEING TO RENT A TOOL.</h2>
            <p>
            For the purposes of this Agreement, (a) a “Power tool” (a “Tool”) is any type of tool and related equipment, such as a power drill or its drill bits made available through TOOL SHARE website (the “Site”); (b) the “Renter” is the person renting the Tool and any other equipment using an account created on the Site, and the “Lister” is the owner or authorized agent for the Tool made available for rent via the Site. This Tool rental agreement (“Agreement”) is a binding agreement between Renter and Lister. TOOL SHARE is a party to this Agreement solely to the extent necessary to facilitate the rental transaction and collect and pay any fees that may be owed hereunder, and is otherwise a third party beneficiary of this Agreement.
            Lister enters into this Agreement and allows Renter to rent and use the Tool, along with any associated equipment (the “Rental”) only on the condition that Renter accepts all of the terms in this Agreement. IF YOU DO NOT ACCEPT THIS AGREEMENT, YOU WILL NOT BE PERMITTED TO RENT THE TOOL OR ANY OTHER EQUIPMENT.
            By entering into this Agreement to rent and use the Tool, Renter acknowledges that:
            <ul>
            <br/>•	he or she has read and understood this Agreement;
            <br/>•	he or she agrees to be bound by all of the terms of this Agreement;
            <br/>•	he or she is knowledgeable with respect to the type of equipment being rented and adjustments required for safe operation and use; and
            <br/>•	if Renter is not properly qualified with respect to power tool equipment, Renter is hereby advised to seek assistance of a qualified professional for proper use of equipment.
            </ul>
            This Agreement is effective on the date Renter agrees to the terms and conditions as provided herein (“Effective Date”). Renter and Lister, intending to be legally bound, agree as follows:
            </p>
            <h2>1. Rental</h2>
            <p>
            <br/><strong>1.1 Agreement to Rent.</strong> By accepting this Agreement, Lister agrees to rent the Tool to Renter, and Renter agrees to rent the Tool from Lister, on the terms and subjects to the conditions set forth herein, and for the period agreed via the Site (the “Rental Period”).
            <br/><strong>1.2 Condition of Tool.</strong> By making the Tool available for rent hereunder, and agreeing to the terms of this Agreement, Lister represents and warrants that (a) he or she is the sole owner of the Tool, or that he or she has full agency or other authority to enter into this Agreement and to rent the Tool to Renter; (b) the Tool has been accurately described on the Site, including any known faults or mechanical issues; (c) except as clearly set forth on the Site, the Tool is in proper working condition, has been professionally maintained, and contains all functionality necessary for the Renter to attain his or her expected use of the Tool during the Rental Period. Unless expressly agreed otherwise, the Rental does not include additional equipment, such as drill bits, sanding belts or grinding wheels.
            <br/><strong>1.3 Refunds and Cancellations.</strong> (a) In the event a Rental is cancelled by either party at least twenty-four (24) hours prior to commencement of the Rental Period, then all funds shall be returned to Renter, less an administrative fee of 10% of the applicable rental fee. (b) In the event that the Rental is cancelled by Renter less than twenty-four (24) hours prior to commencement of the Rental Period, including after the beginning of the Rental Period or because Renter did not pick up the Tool at the agreed time and place (but excluding any cancellation as set forth in 1.3(c)), then Renter shall be charged the full rental price for the Rental as previously agreed via the Site. (c) If upon delivery of the Tool or, within the first twenty-four (24) hours of the Rental Period, Renter reasonably determines that the Tool does not materially conform to the Lister’s description of the Tool, then Renter may notify TOOL SHARE of the deficiency and request a refund. Further, if Lister does not deliver the Tool at the place and time agreed, then Renter shall be entitled to a full refund. If Renter receives a refund under this paragraph 1.3(c), then Lister will in any event be charged the full commission that would have been payable to TOOL SHARE in connection with the Rental. (d) TOOL SHARE shall determine all refunds in its reasonable discretion. In the event either Lister or Renter is not satisfied with TOOL SHARE’s determination, their sole recourse shall be to seek payment or refund of fees directly from the Renter or Lister, as applicable. (e) In the event of the failure of Lister or Renter to appear for scheduled delivery of the Tool, the parties may choose to reschedule the Rental Period rather than accept the fees or refunds set forth above. In such event the parties must arrange such rescheduled delivery through the Site, or otherwise notify TOOL SHARE as soon as practicable. (f) Each party acknowledges that Renters and Listers are entitled to post reviews on the Site with respect to cancelled Rentals.
            <br/><strong>1.4 TOOL SHARE Guarantee.</strong> TOOL SHARE provides a limited guarantee to Listers of up to 300 $ for power tools and up to $ 100 for equipment. Lister understands that the TOOL SHARE Guarantee is limited to loss or damage to the Tool, and does not cover ordinary wear and tear, or any repairs paid for by the Renter. The guarantee does not cover any other property damage, injuries, loss of use or incidental, special or punitive damages – such damages may only be recovered from a Renter. Furthermore, Lister acknowledges and agrees that the TOOL SHARE Guarantee is only available if authentic, accurate and current photographs of the Tool have been included with the listing prior to the Rental period, and to the extent such photographs are sufficient to establish the make, model, components and condition of the Tool and any accessories (if applicable). If Lister is entitled to coverage under the TOOL SHARE Guarantee, the repair or replacement cost of the Tool shall be in TOOL SHARE’s reasonable discretion, in consultation with professional repair or sales personnel knowledgeable in the appropriate field, and shall account for any salvage value of the Tool, if applicable.
            <br/><strong>1.5 Lister Obligations</strong>. If there is damage to a Tool during a Rental, the Lister must notify TOOL SHARE within two (2) weeks of completion of the Rental Period or prior to any subsequent rental, whichever occurs first. If any damage is not reported during such period, then the damage shall be presumed to have occurred subsequent to the Rental and TOOL SHARE Guarantee shall not apply. Lister shall in all events be responsible for the cost of any diagnostic fees, estimates, tune-ups, adjustments, etc. If Renter does not return the Tool at the conclusion of the Rental Period, and does not agree with Lister within twenty-four (24) hours to schedule a new return time, or does not return the Tool at such rescheduled return time, then Lister shall file a report with the applicable police department and provide a copy of such report to TOOL SHARE. In filing the report, Lister is required to notify the police department of the TOOL SHARE Guarantee, and that TOOL SHARE may ultimately be subrogated to Lister’s right to recovery of the Tool. Lister must also authorize the police department to discuss and provide any information regarding the case with TOOL SHARE.
            </p>
            <h2>2. Renter Obligations</h2>
            <p>     
            <br/><strong>2.1 Usage.</strong> No other person may use or otherwise operate the Tool except Renter. Renter must always use the Tool with due care and make sure that the Tool and accessories are adequate for the work to perform (e.g. use wood bits to drill into wooden material only). Renter may use the Tool for private purposes only and may not use the Tool for any professional activity. The usage may not intentionally exceed the reasonable operating duration in the sense that the rental costs are becoming inferior to the depreciation cost of intensive use. In the event that Renter intents to have such an intensive use, Renter must notice and request the Lister’s consent.
            <br/><strong>2.2 Return.</strong> Renter agrees to return the Tool to Lister in the same condition as received, except for ordinary wear and tear on the due date and time and at the location specified by Lister at time of rental. Renter agrees to return the Tool sooner if so demanded by Lister. Renter understands that there will be additional charges if the Tool is returned at a different time, date, or location than indicated in this Agreement, including late charges and additional rental charges at no less than the daily or hourly rate applicable to the Rental. If Renter fails to return the Tool at the agreed date, time and location, and has not agreed with Lister or TOOL SHARE on an alternate delivery time and location within 24 hours of the scheduled delivery time, or Renter fails to return the Tool at the rescheduled time and place, then (a) TOOL SHARE shall determine that Renter does not intend to return the Tool; (b) TOOL SHARE will charge Renter’s payment method for the full retail value of the Tool, as determined in TOOL SHARE’s reasonable discretion, along with any other fees due to TOOL SHARE; (c) TOOL SHARE or Lister may lawfully repossess the Tool; and (d) TOOL SHARE and Lister may exercise any other rights or remedies, and take any other necessary measures, to repossess the Tool and/or collect the full amount owed by Renter hereunder. If Lister fails to appear at the scheduled time and place for return of the Tool, Renter remains responsible for the safe keeping of the Tool. In such event Renter shall contact TOOL SHARE to try to arrange alternate means of return of the Tool, which may be through a public facility. Lister shall be responsible for any fees incurred by TOOL SHARE in connection with such alternate return method, and understands and acknowledges that, if the such fees exceed the amount of the rental fee due Lister, or any other credit amounts in Lister’s account, then the Tool will not be released to Lister until payment arrangement satisfactory to TOOL SHARE in its sole discretion have been made. TOOL SHARE shall not be responsible for any delay or loss of use of the Tool due to Lister’s failure to appear as scheduled or to make alternate payment and return arrangements.
            <br/><strong>2.3 Repossession.</strong> Lister may repossess the Tool through lawful means at any time if: (a) the Tool is used in violation of any law; (b) it appears the Tool is abandoned, (c) the Tool is used in violation of any term or condition in this Agreement, (d) Renter made a misrepresentation to Lister or (e) Renter fails to return the Tool when due. Lister is not required to notify Renter in advance of repossession.
            <br/><strong>2.4 Prohibited Use.</strong> Use of the Tool is restricted to the general geographical area agreed upon by Renter and Lister. Renter will not operate Tool outside of this area and will not remove Tool from this area. Renter agrees not to use or permit the Tool to be used for hire or in any location that operation would be illegal or a nuisance to others. Renter will not use or permit the Tool to be used for an illegal purpose, including the transportation of a controlled substance or contraband. A violation of this paragraph automatically terminates the rental and makes Renter liable to Lister for any penalties, fines, forfeitures, liens, recovery and storage costs, and any related legal expenses associated with a violation of this paragraph.
            <br/><strong>2.5 Damage to Tool.</strong> Renter shall pay Lister for all loss of and/or damage to the Tool, regardless of fault (e.g. Renter agrees to pay for the loss even though someone else caused the damage or is at fault). Renter is also responsible for all theft or vandalism losses, even if Renter is not at fault for making the theft or vandalism possible, and regardless of any measures Renter may have taken to secure or protect the Tool, including any instructions or security devices provided by Lister. If the Tool is damaged, Renter agrees to pay the reasonable costs of repair and diminution in value, if any. If the Tool is lost or damaged beyond reasonable repair (as determined by Lister), Renter shall be responsible for the retail fair market value of the Tool, as determined by TOOL SHARE in its reasonable discretion, less any salvage value if applicable. In addition to the above, Renter shall also be responsible for Lister’s reasonable loss of use of the Tool (“Loss of Use”), a reasonable administrative fee as determined by Lister or specified by law, plus any pick-up and/or storage charges. In the event of theft, Renter shall be responsible for paying Loss of Use at the daily rate for each 24 hours Renter delays in paying the total loss. Renter is also responsible for any loss if Renter: (a) abuses the Tool or uses or operates the Tool other than as specified in this Agreement; (b) uses the Tool recklessly; (c) uses the Tool while under the influence of alcohol or a controlled substance; (d) fails to promptly report an accident to the police and Lister; (d) fails to complete an accident report; (e) obtains the Tool through Renter’s fraud or misrepresentation; or (f) uses the Tool for an illegal purpose. Renter authorizes Lister to collect from a responsible third party any applicable loss and/or damage. In the event Lister obtains a recovery from a third party after Renter has paid Lister for all or part of any loss, Lister will refund to Renter any excess above the amount of the loss plus administrative fees and other collection costs and attorneys’ fees incurred.
            <br/><strong>2.6 Payment.</strong> Renter agrees to pay upon demand all rates, charges, (including those applicable to miscellaneous services and equipment), plus applicable taxes, fees, and surcharges (if applicable), which may apply to the Rental, including, without limitation, charges for loss and/or damage to the Tool. Renter specifically agrees and authorizes TOOL SHARE to apply any charges to the method of payment used by Renter at the time of rental.
            <br/><strong>2.7 Credit Reserve and Payment.</strong> Renter understands that he or she must deposit an amount (to be used against the final bill) equal to the estimated total charge for the Rental at the rates indicated in this Agreement. Renter authorizes TOOL SHARE and Lister to charge any amounts due as a result of the Rental to Renter’s credit card or other payment method provided. Charges for upcoming rentals will be processed at the time Lister accepts the Rental. TOOL SHARE may cause an additional charge authorization to be processed against Renter’s credit card or other payment method as a security deposit, which will be credited back to Renter’s payment method upon satisfactory return of the Tool without damage or delay.
            <br/><strong>2.8 Repairs.</strong> If Renter experiences any malfunctions with the Tool during the Rental period, Renter should immediately notify TOOL SHARE and Lister to obtain authorization for repairs. All unauthorized repairs shall be at Renter’s sole cost and expense. Renter understands that Lister will not reimburse Renter for any authorized repairs without receipts. All repairs needed as a result of the use of the Tool (reasonable wear and tear excepted) will be performed at the normal labor rates and the cost of such repairs, including all parts, shall be paid by Renter.
            <br/><strong>2.9 Ownership.</strong> The Tool, at all times, remains the exclusive property of Lister.
            </p>
            <h2>3. Risk and Liability terms</h2>
            <p>
            <br/><strong>3.1 Acknowledgement of Risks.</strong> Renter understands and acknowledges that using power tools is a hazardous activity that entails known and unanticipated risks which could result in physical or emotional injury or damage to self, to property, or to third parties. Renter understands that such risks cannot be eliminated by Lister without jeopardizing the essential qualities of this activity. Renter understands that protective gear such as gloves, safety shoes and eye protection are recommended, but they do not eliminate the risk and may not reduce the risk of injury in the event of an accident.
            <br/><strong>3.2 Assumption of Risk.</strong> RENTER KNOWINGLY, INTELLIGENTLY AND VOLUNTARILY ASSUME ALL RISKS RELATED TO THE OPERATION AND POSSESSION OF THE TOOL, INCLUDING, WITHOUT LIMITATION ANY BODILY INJURY OR DEATH TO ANY PERSON, OR PROPERTY DAMAGE TO ANY PROPERTY WHICH MAY RESULT FROM THE OPERATION OF THE TOOL OR POSSESSION OF THE TOOL EVEN IF SUCH LOSS OR DAMAGE IS DUE TO ANY NEGLIGENCE OF LISTER, TOOL SHARE, THEIR AGENTS, EMPLOYEES, OFFICERS, PARTNERS, MEMBERS, SUCCESSORS AND/OR ASSIGNS. DESPITE KNOWING ALL ASSOCIATED RISKS, RENTER FREELY ASSUMES ALL RISKS OF PERSONAL INJURY AND/OR DAMAGE IN THE OPERATION OF THIS TOOL AND RENTER AGREES TO HOLD LISTER AND TOOL SHARE HARMLESS FROM ALL CLAIMS OF INJURY OR DAMAGE.
            <br/><strong>3.3 Waiver and Release.</strong> In consideration of Lister renting the Tool, Renter specifically releases and forever discharges Lister, TOOL SHARE, and their affiliates, officers, agents, and employees from any and all liability or claims for injury, illness, death or loss of or damage to property which Renter may suffer while renting this Tool and participating in associated activities. This discharge specifically includes, but is not limited to, liability or claims for injury, illness, death or damage caused by the negligence of Lister, TOOL SHARE, or their affiliates, officers, members, managers, agents, or employees. It is the express intent of this Agreement that Renter release Lister and TOOL SHARE and hold them harmless from all liability for any such property loss or damage, personal injury or loss of life, whether caused by the negligence of Lister or TOOL SHARE or whether based upon breach of contract, breach of warranty, or any other legal theory. In agreeing to this Agreement, Renter fully recognizes that if injury, illness, death or damage occurs while engaged in renting this Tool or participating in works any other activity associated with the Tool, Renter will have no right to make a claim or file a lawsuit against Lister, TOOL SHARE or their affiliates, officers, members, agents or employees, even if any of them negligently cause any injury, illness, death or damage.
            <br/><strong>3.4 Indemnification.</strong> Renter agrees to indemnify and hold harmless Lister and TOOL SHARE and their subsidiaries, agents, licensors, members, managers, officers and other affiliated companies, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs and expenses (including attorney’s fees) arising from, related to, or in any way connected with, or resulting from Renter’s participation in this activity or use of the Tool, including the possession, use, operation, or return of the Tool, and including any such claims which allege negligent acts or omissions on the part of Lister or TOOL SHARE. Should Lister, TOOL SHARE or anyone acting on their behalf, be required to incur attorney’s fees and costs to enforce this agreement, Renter agrees to indemnify and hold them harmless for all such fees and costs.
            <br/><strong>3.5 Third Party Claims.</strong> Neither Lister nor TOOL SHARE shall be responsible if Renter causes injury to another person or if Renter damages any personal property of another. Renter agrees to protect, defend, indemnify and hold Lister and TOOL SHARE harmless and pay any claim, including attorneys’ fees, brought by a third party arising out of Renter’s use of the Tool and for any liability associated with any personal accident/injury as a result of Renter’s use of the Tool.
            <br/><strong>3.6 Insurance.</strong> Renter represents and warrants that he or she has adequate insurance to cover any injury or damage Renter may cause or suffer while participating in the activity, and in all events Renter agrees to bear the costs of such injury or damage. Renter understands and agrees that Lister and/or TOOL SHARE may make a claim against any insurance coverage Renter maintains, whether liability, casualty, personal or health insurance, in the event of any loss, injury, death or damage to person or property while using or operating the Tool. Neither the maintenance of, or failure to maintain, adequate insurance shall relieve Renter of any liability hereunder.
            <br/><strong>3.7 Physical Condition.</strong> Renter represents and warrants that he or she should be in good physical health to operate the Tool. Renter certifies that Renter has no medical or physical conditions which could interfere with Renter’s safety in this activity, or else Renter is willing to assume all liability, damages or costs that may be created, directly or indirectly, by any such condition.
            </p>
            <h2>4. General Provisions</h2>
            <p>
            <br/><strong>4.1 No Warranty.</strong> THE TOOL IS PROVIDED TO RENTER ON AN “AS IS” AND “AS AVAILABLE” BASIS. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE TOOL IS PROVIDED WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTY OF MERCHANTABILITY AND THE IMPLIED WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE. WITHOUT LIMITING THE FOREGOING, LISTER DOES NOT WARRANT THAT THE TOOL OR ANY RENTAL WILL MEET RENTER’S REQUIREMENTS.
            <br/><strong>4.2 Limitation of Liability.</strong>
            <br/><strong>(a)</strong> TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL LISTER OR TOOL SHARE, THEIR SUBSIDIARIES, AFFILIATES, AGENTS, MEMBERS, MANAGERS, DIRECTORS, OFFICERS, EMPLOYEES, OR SUPPLIERS BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES, THAT RESULT FROM ANY RENTAL OR THE USE OF, OR INABILITY TO USE, THE TOOL.
            <br/><strong>(b)</strong> IF LISTER OR TOOL SHARE, OR THEIR AFFILIATES, AGENTS, DIRECTORS, EMPLOYEES, OR SUPPLIERS ARE FOUND TO BE LIABLE, SUCH LIABILITY TO RENTER OR TO ANY THIRD PARTY IS LIMITED TO THE GREATER OF (A) THE TOTAL FEES ACTUALLY PAID HEREUNDER OR (B) $ 100.
            <br/><strong>(c)</strong> THIS LIMITATION OF LIABILITY SECTION APPLIES WHETHER THE ALLEGED LIABILITY IS BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER BASIS, EVEN IF TOOL SHARE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.
            <br/><strong>4.3 Assignment.</strong> This Agreement, and any rights and licenses granted hereunder, may not be transferred or assigned by either Lister or Renter.
            <br/><strong>4.4 Third Party Beneficiary.</strong> TOOL SHARE shall be an intended third party beneficiary of this Agreement with the full rights to enforce the provisions relating to TOOL SHARE herein.
            <br/><strong>4.5 Governing Law.</strong> This Agreement shall be governed by Belgian law, without respect to its conflict of laws principles. The application of the United Nations Convention on Contracts for the International Sale of Goods is expressly excluded. Any claim or dispute between Renter and Lister that arises in whole or in part from the rental of the Tool shall be decided exclusively by a court of competent jurisdiction closest to Lister’s residence.
            <br/><strong>4.6 No Waiver.</strong> No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term, and a party’s failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision.
            <br/><strong>4.7 Entire Agreement/Severability.</strong> This Agreement shall constitute the entire agreement between Renter and Lister concerning the rental of the Tool. If a court of competent jurisdiction deems any provision of this Agreement invalid, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect.
            </p>
            
        </div>
    )
}